const fs = require('fs');

const vocabByLevel = {
    N5: {
        nouns: [
            { kanji: '学生', hiragana: 'がくせい', meaning: '学生' },
            { kanji: '本', hiragana: 'ほん', meaning: '书' },
            { kanji: '花', hiragana: 'はな', meaning: '花' },
            { kanji: '雨', hiragana: 'あめ', meaning: '雨' },
            { kanji: '日本人', hiragana: 'にほんじん', meaning: '日本人' },
            { kanji: '先生', hiragana: 'せんせい', meaning: '老师' },
            { kanji: '銀行', hiragana: 'ぎんこう', meaning: '银行' },
            { kanji: '部屋', hiragana: 'へや', meaning: '房间' },
            { kanji: '椅子', hiragana: 'いす', meaning: '椅子' },
            { kanji: '机', hiragana: 'つくえ', meaning: '桌子' },
            { kanji: '朝', hiragana: 'あさ', meaning: '早上' },
            { kanji: '夜', hiragana: 'よる', meaning: '晚上' },
            { kanji: '今日', hiragana: 'きょう', meaning: '今天' },
            { kanji: '昨日', hiragana: 'きのう', meaning: '昨天' },
            { kanji: '明日', hiragana: 'あした', meaning: '明天' },
            { kanji: '時間', hiragana: 'じかん', meaning: '时间' },
            { kanji: '水', hiragana: 'みず', meaning: '水' },
            { kanji: '車', hiragana: 'くるま', meaning: '车' },
            { kanji: '電車', hiragana: 'でんしゃ', meaning: '电车' },
            { kanji: '駅', hiragana: 'えき', meaning: '车站' },
            { kanji: '病院', hiragana: 'びょういん', meaning: '医院' },
            { kanji: '薬', hiragana: 'くすり', meaning: '药' },
            { kanji: '手紙', hiragana: 'てがみ', meaning: '信' },
            { kanji: '電話', hiragana: 'でんわ', meaning: '电话' },
            { kanji: '友達', hiragana: 'ともだち', meaning: '朋友' },
            { kanji: '家族', hiragana: 'かぞく', meaning: '家人' },
            { kanji: '肉', hiragana: 'にく', meaning: '肉' },
            { kanji: '魚', hiragana: 'さかな', meaning: '鱼' },
            { kanji: '野菜', hiragana: 'やさい', meaning: '蔬菜' },
            { kanji: '果物', hiragana: 'くだもの', meaning: '水果' },
            { kanji: 'ご飯', hiragana: 'ごはん', meaning: '米饭' },
            { kanji: '新聞', hiragana: 'しんぶん', meaning: '报纸' },
            { kanji: 'テレビ', hiragana: 'テレビ', meaning: '电视' },
            { kanji: '時計', hiragana: 'とけい', meaning: '时钟' },
            { kanji: '傘', hiragana: 'かさ', meaning: '伞' },
            { kanji: '鞄', hiragana: 'かばん', meaning: '包' },
            { kanji: '帽子', hiragana: 'ぼうし', meaning: '帽子' },
            { kanji: '靴', hiragana: 'くつ', meaning: '鞋子' },
            { kanji: '公園', hiragana: 'こうえん', meaning: '公园' },
            { kanji: '図書館', hiragana: 'としょかん', meaning: '图书馆' },
            { kanji: '学校', hiragana: 'がっこう', meaning: '学校' },
            { kanji: '会社', hiragana: 'かいしゃ', meaning: '公司' },
            { kanji: '店', hiragana: 'みせ', meaning: '店' },
            { kanji: 'レストラン', hiragana: 'レストラン', meaning: '餐厅' },
            { kanji: 'カフェ', hiragana: 'カフェ', meaning: '咖啡馆' },
            { kanji: 'ホテル', hiragana: 'ホテル', meaning: '酒店' },
            { kanji: '山', hiragana: 'やま', meaning: '山' },
            { kanji: '川', hiragana: 'かわ', meaning: '河流' },
            { kanji: '海', hiragana: 'うみ', meaning: '海' },
            { kanji: '空', hiragana: 'そら', meaning: '天空' },
            { kanji: '星', hiragana: 'ほし', meaning: '星星' },
            { kanji: '月', hiragana: 'つき', meaning: '月亮' },
            { kanji: '犬', hiragana: 'いぬ', meaning: '狗' },
            { kanji: '猫', hiragana: 'ねこ', meaning: '猫' },
            { kanji: '鳥', hiragana: 'とり', meaning: '鸟' },
            { kanji: '林檎', hiragana: 'りんご', meaning: '苹果' },
            { kanji: '蜜柑', hiragana: 'みかん', meaning: '橘子' },
            { kanji: '豆腐', hiragana: 'とうふ', meaning: '豆腐' },
            { kanji: '味噌', hiragana: 'みそ', meaning: '味噌' },
            { kanji: '醤油', hiragana: 'しょうゆ', meaning: '酱油' },
            { kanji: '洗濯', hiragana: 'せんたく', meaning: '洗涤' },
            { kanji: '掃除', hiragana: 'そうじ', meaning: '打扫' },
            { kanji: '料理', hiragana: 'りょうり', meaning: '料理' },
            { kanji: '散歩', hiragana: 'さんぽ', meaning: '散步' },
            { kanji: '宿題', hiragana: 'しゅくだい', meaning: '作业' },
            { kanji: '洗濯物', hiragana: 'せんたくもの', meaning: '洗好的衣物' },
            { kanji: '眼鏡', hiragana: 'めがね', meaning: '眼镜' },
            { kanji: '医者', hiragana: 'いしゃ', meaning: '医生' },
            { kanji: '看護師', hiragana: 'かんごし', meaning: '护士' },
            { kanji: '弁護士', hiragana: 'べんごし', meaning: '律师' },
            { kanji: '社員', hiragana: 'しゃいん', meaning: '公司职员' },
            { kanji: '警察官', hiragana: 'けいさつかん', meaning: '警察' },
            { kanji: '消防士', hiragana: 'しょうぼうし', meaning: '消防员' },
            { kanji: '運転手', hiragana: 'うんてんしゅ', meaning: '司机' },
            { kanji: '料理人', hiragana: 'りょうりにん', meaning: '厨师' },
            { kanji: '店員', hiragana: 'てんいん', meaning: '店员' },
            { kanji: '歌手', hiragana: 'かしゅ', meaning: '歌手' },
            { kanji: '俳優', hiragana: 'はいゆう', meaning: '演员' },
            { kanji: '画家', hiragana: 'がか', meaning: '画家' },
            { kanji: '作家', hiragana: 'さっか', meaning: '作家' }
        ],
        adjectives: [
            { kanji: '甘い', hiragana: 'あまい', meaning: '甜的' },
            { kanji: '寒い', hiragana: 'さむい', meaning: '冷的' },
            { kanji: '熱い', hiragana: 'あつい', meaning: '热的' },
            { kanji: '冷たい', hiragana: 'つめたい', meaning: '冷的' },
            { kanji: '美味しい', hiragana: 'おいしい', meaning: '好吃的' },
            { kanji: 'まずい', hiragana: 'まずい', meaning: '难吃的' },
            { kanji: '忙しい', hiragana: 'いそがしい', meaning: '忙碌的' },
            { kanji: '楽しい', hiragana: 'たのしい', meaning: '快乐的' },
            { kanji: '難しい', hiragana: 'むずかしい', meaning: '困难的' },
            { kanji: '易しい', hiragana: 'やさしい', meaning: '简单的' },
            { kanji: '新しい', hiragana: 'あたらしい', meaning: '新的' },
            { kanji: '古い', hiragana: 'ふるい', meaning: '旧的' },
            { kanji: '高い', hiragana: 'たかい', meaning: '高的' },
            { kanji: '低い', hiragana: 'ひくい', meaning: '低的' },
            { kanji: '長い', hiragana: 'ながい', meaning: '长的' },
            { kanji: '短い', hiragana: 'みじかい', meaning: '短的' },
            { kanji: '広い', hiragana: 'ひろい', meaning: '宽广的' },
            { kanji: '狭い', hiragana: 'せまい', meaning: '狭窄的' },
            { kanji: '重い', hiragana: 'おもい', meaning: '重的' },
            { kanji: '軽い', hiragana: 'かるい', meaning: '轻的' },
            { kanji: '強い', hiragana: 'つよい', meaning: '强的' },
            { kanji: '弱い', hiragana: 'よわい', meaning: '弱的' },
            { kanji: '速い', hiragana: 'はやい', meaning: '快的' },
            { kanji: '遅い', hiragana: 'おそい', meaning: '慢的' },
            { kanji: '遠い', hiragana: 'とおい', meaning: '远的' },
            { kanji: '近い', hiragana: 'ちかい', meaning: '近的' },
            { kanji: '深い', hiragana: 'ふかい', meaning: '深的' },
            { kanji: '浅い', hiragana: 'あさい', meaning: '浅的' },
            { kanji: '多い', hiragana: 'おおい', meaning: '多的' },
            { kanji: '少ない', hiragana: 'すくない', meaning: '少的' },
            { kanji: '可愛い', hiragana: 'かわいい', meaning: '可爱的' },
            { kanji: '美しい', hiragana: 'うつくしい', meaning: '美丽的' },
            { kanji: '恥ずかしい', hiragana: 'はずかしい', meaning: '害羞的' },
            { kanji: '静かな', hiragana: 'しずかな', meaning: '安静的' },
            { kanji: '賑やかな', hiragana: 'にぎやかな', meaning: '热闹的' },
            { kanji: '有名な', hiragana: 'ゆうめいな', meaning: '有名的' },
            { kanji: '新鮮な', hiragana: 'しんせんな', meaning: '新鲜的' },
            { kanji: '危険な', hiragana: 'きけんな', meaning: '危险的' },
            { kanji: '安全な', hiragana: 'あんぜんな', meaning: '安全的' },
            { kanji: '便利な', hiragana: 'べんりな', meaning: '方便的' },
            { kanji: '不便な', hiragana: 'ふべんな', meaning: '不方便的' },
            { kanji: '簡単な', hiragana: 'かんたんな', meaning: '简单的' },
            { kanji: '複雑な', hiragana: 'ふくざつな', meaning: '复杂的' },
            { kanji: '丈夫な', hiragana: 'じょうぶな', meaning: '坚固的' },
            { kanji: '汚い', hiragana: 'きたない', meaning: '脏的' },
            { kanji: '早い', hiragana: 'はやい', meaning: '早的' },
            { kanji: '明るい', hiragana: 'あかるい', meaning: '明亮的' },
            { kanji: '暗い', hiragana: 'くらい', meaning: '暗的' }
        ],
        verbs: [
            { kanji: '会う', hiragana: 'あう', meaning: '见面' },
            { kanji: '洗う', hiragana: 'あらう', meaning: '洗' },
            { kanji: '歩く', hiragana: 'あるく', meaning: '走' },
            { kanji: '言う', hiragana: 'いう', meaning: '说' },
            { kanji: '歌う', hiragana: 'うたう', meaning: '唱' },
            { kanji: '書く', hiragana: 'かく', meaning: '写' },
            { kanji: '聞く', hiragana: 'きく', meaning: '听' },
            { kanji: '消す', hiragana: 'けす', meaning: '关掉' },
            { kanji: '来る', hiragana: 'くる', meaning: '来' },
            { kanji: '知る', hiragana: 'しる', meaning: '知道' },
            { kanji: '死ぬ', hiragana: 'しぬ', meaning: '死' },
            { kanji: '吸う', hiragana: 'すう', meaning: '吸' },
            { kanji: '座る', hiragana: 'すわる', meaning: '坐' },
            { kanji: '立つ', hiragana: 'たつ', meaning: '站' },
            { kanji: '食べる', hiragana: 'たべる', meaning: '吃' },
            { kanji: '使う', hiragana: 'つかう', meaning: '使用' },
            { kanji: '作る', hiragana: 'つくう', meaning: '做' },
            { kanji: '出る', hiragana: 'でる', meaning: '出' },
            { kanji: '投げる', hiragana: 'なげる', meaning: '投' },
            { kanji: '飲む', hiragana: 'のむ', meaning: '喝' },
            { kanji: '話す', hiragana: 'はなす', meaning: '说' },
            { kanji: '始まる', hiragana: 'はじまる', meaning: '开始' },
            { kanji: '働く', hiragana: 'はたらく', meaning: '工作' },
            { kanji: '弾く', hiragana: 'ひく', meaning: '弹' },
            { kanji: '待つ', hiragana: 'まつ', meaning: '等' },
            { kanji: '持つ', hiragana: 'もつ', meaning: '拿' },
            { kanji: '読む', hiragana: 'よむ', meaning: '读' },
            { kanji: '呼ぶ', hiragana: 'よぶ', meaning: '叫' },
            { kanji: '起きる', hiragana: 'おきる', meaning: '起床' },
            { kanji: '落ちる', hiragana: 'おちる', meaning: '落下' },
            { kanji: '変える', hiragana: 'かえる', meaning: '改变' },
            { kanji: '泊まる', hiragana: 'とまる', meaning: '住宿' },
            { kanji: '戻る', hiragana: 'もどる', meaning: '返回' },
            { kanji: 'やる', hiragana: 'やる', meaning: '做' }
        ]
    },
    N4: {
        nouns: [
            { kanji: '手続き', hiragana: 'てつづき', meaning: '手续' },
            { kanji: '目的', hiragana: 'もくてき', meaning: '目的' },
            { kanji: '結果', hiragana: 'けっか', meaning: '结果' },
            { kanji: '原因', hiragana: 'げんいん', meaning: '原因' },
            { kanji: '理由', hiragana: 'りゆう', meaning: '理由' },
            { kanji: '習慣', hiragana: 'しゅうかん', meaning: '习惯' },
            { kanji: '性格', hiragana: 'せいかく', meaning: '性格' },
            { kanji: '気分', hiragana: 'きぶん', meaning: '心情' },
            { kanji: '雰囲気', hiragana: 'ふんいき', meaning: '氛围' },
            { kanji: '状況', hiragana: 'じょうきょう', meaning: '状况' },
            { kanji: '環境', hiragana: 'かんきょう', meaning: '环境' },
            { kanji: '問題', hiragana: 'もんだい', meaning: '问题' },
            { kanji: '対策', hiragana: 'たいさく', meaning: '对策' },
            { kanji: '相談', hiragana: 'そうだん', meaning: '商量' },
            { kanji: '説明', hiragana: 'せつめい', meaning: '说明' },
            { kanji: '提案', hiragana: 'ていあん', meaning: '提案' },
            { kanji: '約束', hiragana: 'やくそく', meaning: '约定' },
            { kanji: '経験', hiragana: 'けいけん', meaning: '经验' },
            { kanji: '失敗', hiragana: 'しっぱい', meaning: '失败' },
            { kanji: '成功', hiragana: 'せいこう', meaning: '成功' },
            { kanji: '努力', hiragana: 'どりょく', meaning: '努力' },
            { kanji: '夢', hiragana: 'ゆめ', meaning: '梦想' },
            { kanji: '希望', hiragana: 'きぼう', meaning: '希望' },
            { kanji: '決意', hiragana: 'けつい', meaning: '决心' },
            { kanji: '考え', hiragana: 'かんがえ', meaning: '想法' },
            { kanji: '意見', hiragana: 'いけん', meaning: '意见' },
            { kanji: '価値観', hiragana: 'かちかん', meaning: '价值观' },
            { kanji: '両方', hiragana: 'りょうほう', meaning: '两者' },
            { kanji: '全体', hiragana: 'ぜんたい', meaning: '全体' },
            { kanji: '部分', hiragana: 'ぶぶん', meaning: '部分' },
            { kanji: '内容', hiragana: 'ないよう', meaning: '内容' },
            { kanji: '形式', hiragana: 'けいしき', meaning: '形式' },
            { kanji: '本質', hiragana: 'ほんしつ', meaning: '本质' },
            { kanji: '現象', hiragana: 'げんしょう', meaning: '现象' },
            { kanji: '背景', hiragana: 'はいけい', meaning: '背景' },
            { kanji: '影響', hiragana: 'えいきょう', meaning: '影响' },
            { kanji: '効果', hiragana: 'こうか', meaning: '效果' },
            { kanji: '意味', hiragana: 'いみ', meaning: '意思' },
            { kanji: '特色', hiragana: 'とくしょく', meaning: '特色' },
            { kanji: '特徴', hiragana: 'とくちょう', meaning: '特征' },
            { kanji: '利点', hiragana: 'りてん', meaning: '优点' },
            { kanji: '欠点', hiragana: 'けってん', meaning: '缺点' },
            { kanji: '長所', hiragana: 'ちょうしょ', meaning: '长处' },
            { kanji: '短所', hiragana: 'たんしょ', meaning: '短处' },
            { kanji: '強み', hiragana: 'つよみ', meaning: '强项' },
            { kanji: '弱み', hiragana: 'よわみ', meaning: '弱点' },
            { kanji: '側面', hiragana: 'そくめん', meaning: '侧面' },
            { kanji: '観点', hiragana: 'かんてん', meaning: '观点' },
            { kanji: '結論', hiragana: 'けつ론', meaning: '结论' },
            { kanji: '要点', hiragana: 'ようてん', meaning: '要点' },
            { kanji: '重点', hiragana: 'じゅうてん', meaning: '重点' },
            { kanji: '核心', hiragana: 'かくしん', meaning: '核心' },
            { kanji: '根拠', hiragana: 'こんきょ', meaning: '根据' },
            { kanji: '証拠', hiragana: 'しょうこ', meaning: '证据' },
            { kanji: '材料', hiragana: 'ざいりょう', meaning: '材料' },
            { kanji: '構成', hiragana: 'こうせい', meaning: '构成' },
            { kanji: '構造', hiragana: 'こうぞう', meaning: '构造' },
            { kanji: '組織', hiragana: 'そしき', meaning: '组织' },
            { kanji: '原理', hiragana: 'げんり', meaning: '原理' },
            { kanji: '原則', hiragana: 'げんそく', meaning: '原则' },
            { kanji: '定義', hiragana: 'ていぎ', meaning: '定义' },
            { kanji: '概念', hiragana: 'がいねん', meaning: '概念' },
            { kanji: '範囲', hiragana: 'はんい', meaning: '范围' },
            { kanji: '限度', hiragana: 'げんど', meaning: '限度' },
            { kanji: '境界', hiragana: 'きょうかい', meaning: '境界' },
            { kanji: '限界', hiragana: 'げんかい', meaning: '界限' },
            { kanji: '区別', hiragana: 'くべつ', meaning: '区别' },
            { kanji: '差異', hiragana: 'さい', meaning: '差异' },
            { kanji: '共通点', hiragana: 'きょうつうてん', meaning: '共同点' },
            { kanji: '相違点', hiragana: 'そういてん', meaning: '不同点' },
            { kanji: '類似点', hiragana: 'るいじてん', meaning: '类似点' },
            { kanji: '類似', hiragana: 'るいじ', meaning: '类似' },
            { kanji: '比較', hiragana: 'ひかく', meaning: '比较' },
            { kanji: '対照', hiragana: 'たいしょう', meaning: '对照' },
            { kanji: '対立', hiragana: 'たいりつ', meaning: '对立' },
            { kanji: '調和', hiragana: 'ちょうわ', meaning: '调和' },
            { kanji: '均衡', hiragana: 'きんこう', meaning: '均衡' }
        ],
        adjectives: [
            { kanji: '特別な', hiragana: 'とくべつな', meaning: '特别的' },
            { kanji: '一般的な', hiragana: 'いっぱんてきな', meaning: '一般的' },
            { kanji: '必要な', hiragana: 'ひつような', meaning: '必要的' },
            { kanji: '重要な', hiragana: 'じゅうような', meaning: '重要的' },
            { kanji: '当然の', hiragana: 'とうぜんの', meaning: '当然的' },
            { kanji: '意外な', hiragana: 'いがいの', meaning: '意外的' },
            { kanji: '不思議な', hiragana: 'ふしぎな', meaning: '不可思议的' },
            { kanji: '複雑な', hiragana: 'ふくざつな', meaning: '复杂的' },
            { kanji: '単純な', hiragana: 'たんじゅんな', meaning: '单纯的' },
            { kanji: '具体的な', hiragana: 'ぐたいてきな', meaning: '具体的' },
            { kanji: '抽象的な', hiragana: 'ちゅうしょうてきな', meaning: '抽象的' },
            { kanji: '明確な', hiragana: 'めいかくな', meaning: '明确的' },
            { kanji: '曖昧な', hiragana: 'あいまいな', meaning: '模糊的' },
            { kanji: '主观的な', hiragana: 'しゅかんてきな', meaning: '主观的' },
            { kanji: '客观的な', hiragana: 'きゃっかんてきな', meaning: '客观的' },
            { kanji: '積極的な', hiragana: 'せっきょくてきな', meaning: '积极的' },
            { kanji: '消極的な', hiragana: 'しょうきょくてきな', meaning: '消极的' },
            { kanji: '肯定的な', hiragana: 'こうていてきな', meaning: '肯定的' },
            { kanji: '否定的な', hiragana: 'ひていてきな', meaning: '否定的' },
            { kanji: '建设的な', hiragana: 'けんせつてきな', meaning: '建设性的' },
            { kanji: '破壊的な', hiragana: 'はかいてきな', meaning: '破坏性的' },
            { kanji: '直接的な', hiragana: 'ちょくせつてきな', meaning: '直接的' },
            { kanji: '间接的な', hiragana: 'かんせつてきな', meaning: '间接的' },
            { kanji: '現実的な', hiragana: 'げんじつてきな', meaning: '现实的' },
            { kanji: '合理的な', hiragana: 'ごうりてきな', meaning: '合理的' },
            { kanji: '論理的な', hiragana: 'ろいろんてきな', meaning: '逻辑的' },
            { kanji: '体系的な', hiragana: 'たいけいてきな', meaning: '系统的' },
            { kanji: '詳細な', hiragana: 'しょうさな', meaning: '详细的' },
            { kanji: '簡潔な', hiragana: 'かんけつな', meaning: '简洁的' },
            { kanji: '精密な', hiragana: 'せいみつな', meaning: '精密的' },
            { kanji: '大まかな', hiragana: 'おおまかな', meaning: '粗略的' },
            { kanji: '正確な', hiragana: 'せいかくな', meaning: '准确的' },
            { kanji: '透明な', hiragana: 'とうめいな', meaning: '透明的' },
            { kanji: '静かな', hiragana: 'しずかな', meaning: '安静的' },
            { kanji: '穏やかな', hiragana: 'おだやかな', meaning: '温和的' },
            { kanji: '激しい', hiragana: 'はげしい', meaning: '激烈的' },
            { kanji: '静かな', hiragana: 'しずかな', meaning: '寂静的' }
        ],
        verbs: [
            { kanji: '感じる', hiragana: 'かんじる', meaning: '感觉' },
            { kanji: '考える', hiragana: 'かんがえる', meaning: '思考' },
            { kanji: '信じる', hiragana: 'しんじる', meaning: '相信' },
            { kanji: '疑う', hiragana: 'うたがう', meaning: '怀疑' },
            { kanji: '期待する', hiragana: 'きたいする', meaning: '期待' },
            { kanji: '希望する', hiragana: 'きぼうする', meaning: '希望' },
            { kanji: '驚く', hiragana: 'おどろく', meaning: '惊讶' },
            { kanji: '悲しむ', hiragana: 'かなしむ', meaning: '悲伤' },
            { kanji: '喜ぶ', hiragana: 'よろこぶ', meaning: '高兴' },
            { kanji: '怒る', hiragana: 'おこる', meaning: '生气' },
            { kanji: '苦しむ', hiragana: 'くるしむ', meaning: '痛苦' },
            { kanji: '悩む', hiragana: 'なやむ', meaning: '烦恼' },
            { kanji: '迷う', hiragana: 'まよう', meaning: '迷惘' },
            { kanji: '决心する', hiragana: 'けつしんする', meaning: '决心' },
            { kanji: '努力する', hiragana: 'どりょくする', meaning: '努力' },
            { kanji: '奋斗する', hiragana: 'ふんとうする', meaning: '奋斗' },
            { kanji: '成功する', hiragana: 'せいこうする', meaning: '成功' },
            { kanji: '失败する', hiragana: 'しっぱいする', meaning: '失败' },
            { kanji: '理解する', hiragana: 'りかいする', meaning: '理解' },
            { kanji: '误解する', hiragana: 'ごかいする', meaning: '误解' },
            { kanji: '忘れる', hiragana: 'わすれる', meaning: '忘记' },
            { kanji: '思い出す', hiragana: 'おもいだす', meaning: '想起' },
            { kanji: '気づく', hiragana: 'きづく', meaning: '注意到' },
            { kanji: '発見する', hiragana: 'はっけんする', meaning: '发现' },
            { kanji: '发明する', hiragana: 'はつめいする', meaning: '发明' },
            { kanji: '创造する', hiragana: 'そうぞうする', meaning: '创造' },
            { kanji: '破坏する', hiragana: 'はかいする', meaning: '破坏' },
            { kanji: '影响する', hiragana: 'えいきょうする', meaning: '影响' },
            { kanji: '変化する', hiragana: 'へんかする', meaning: '变化' },
            { kanji: '成长する', hiragana: 'せいちょうする', meaning: '成长' },
            { kanji: '进步する', hiragana: 'しんぽする', meaning: '进步' },
            { kanji: '退步する', hiragana: 'たいほする', meaning: '退步' },
            { kanji: '发展する', hiragana: 'はってんする', meaning: '发展' },
            { kanji: '增加する', hiragana: 'ぞうかする', meaning: '增加' },
            { kanji: '减少する', hiragana: 'げんしょうする', meaning: '减少' },
            { kanji: '扩大する', hiragana: 'かくだいする', meaning: '扩大' },
            { kanji: '缩小する', hiragana: 'しゅくしょうする', meaning: '缩小' },
            { kanji: '强化する', hiragana: 'きょうかする', meaning: '强化' },
            { kanji: '改善する', hiragana: 'かいぜんする', meaning: '改善' },
            { kanji: '维持する', hiragana: 'いじする', meaning: '维持' },
            { kanji: '持续する', hiragana: 'じぞくする', meaning: '持续' },
            { kanji: '中断する', hiragana: 'ちゅうだんする', meaning: '中断' },
            { kanji: '终止する', hiragana: 'しゅうしする', meaning: '终止' },
            { kanji: '继续する', hiragana: 'けいぞくする', meaning: '继续' }
        ]
    },
    N3: {
        nouns: [
            { kanji: '矛盾', hiragana: 'むじゅん', meaning: '矛盾' },
            { kanji: '曖昧', hiragana: 'あいまい', meaning: '曖昧' },
            { kanji: '革新的', hiragana: 'かくしんてき', meaning: '创新的' },
            { kanji: '顕著', hiragana: 'けんちょ', meaning: '显著的' },
            { kanji: '盛大', hiragana: 'せいだい', meaning: '盛大的' },
            { kanji: '優先', hiragana: 'ゆうせん', meaning: '优先' },
            { kanji: '深刻', hiragana: 'しんこく', meaning: '深刻的' },
            { kanji: '緊急', hiragana: 'きんきゅう', meaning: '紧急的' },
            { kanji: '重大', hiragana: 'じゅうだい', meaning: '重大的' },
            { kanji: '緊迫', hiragana: 'きんぱく', meaning: '紧迫的' },
            { kanji: '切実', hiragana: 'せつじつ', meaning: '迫切的' },
            { kanji: '鋭い', hiragana: 'するどい', meaning: '尖锐的' },
            { kanji: '微妙', hiragana: 'びみょう', meaning: '微妙的' },
            { kanji: '敏感', hiragana: 'びんかん', meaning: '敏感的' },
            { kanji: '鈍感', hiragana: 'どんかん', meaning: '迟钝的' },
            { kanji: '華麗', hiragana: 'かれい', meaning: '华丽的' },
            { kanji: '地味', hiragana: 'じみ', meaning: '朴素的' },
            { kanji: '鮮明', hiragana: 'せんめい', meaning: '鲜明的' },
            { kanji: '明瞭', hiragana: 'めいりょう', meaning: '明确的' },
            { kanji: '具体的', hiragana: 'ぐたいてき', meaning: '具体的' },
            { kanji: '抽象的', hiragana: 'ちゅうしょうてき', meaning: '抽象的' },
            { kanji: '客観的', hiragana: 'きゃっかんてき', meaning: '客观的' },
            { kanji: '主観的', hiragana: 'しゅかんてき', meaning: '主观的' },
            { kanji: '積極的', hiragana: 'せっきょくてき', meaning: '积极的' },
            { kanji: '消極的', hiragana: 'しょうきょくてき', meaning: '消极的' },
            { kanji: '肯定的', hiragana: 'こうていてき', meaning: '肯定的' },
            { kanji: '否定的', hiragana: 'ひていてき', meaning: '否定的' },
            { kanji: '建設的', hiragana: 'けんせつてき', meaning: '建设性的' },
            { kanji: '破壊的', hiragana: 'はかいてき', meaning: '破坏性的' },
            { kanji: '革新的', hiragana: 'かくしんてき', meaning: '革新性的' },
            { kanji: '伝統的', hiragana: 'でんとうてき', meaning: '传统性的' },
            { kanji: '画期的', hiragana: 'かっきてき', meaning: '划时代的' },
            { kanji: '前例', hiragana: 'ぜんれい', meaning: '先例' },
            { kanji: '慣例', hiragana: 'かんれい', meaning: '惯例' },
            { kanji: '異例', hiragana: 'いれい', meaning: '例外' },
            { kanji: '特例', hiragana: 'とくれい', meaning: '特别例子' },
            { kanji: '定例', hiragana: 'ていれい', meaning: '惯例' },
            { kanji: '慣行', hiragana: 'かんこう', meaning: '惯例' },
            { kanji: '通例', hiragana: 'つうれい', meaning: '通常' },
            { kanji: '例外的', hiragana: 'れいがいてき', meaning: '例外的' },
            { kanji: '並外れた', hiragana: 'なみはずれた', meaning: '非凡的' },
            { kanji: '非凡', hiragana: 'ひぼん', meaning: '非凡' },
            { kanji: '傑作', hiragana: 'けっさく', meaning: '杰作' },
            { kanji: '偉業', hiragana: 'いぎょう', meaning: '伟业' },
            { kanji: '偉大', hiragana: 'いだい', meaning: '伟大的' },
            { kanji: '壮大', hiragana: 'そうだい', meaning: '壮大的' },
            { kanji: '大規模', hiragana: 'だいきぼ', meaning: '大规模的' },
            { kanji: '小規模', hiragana: 'しょうきぼ', meaning: '小规模的' },
            { kanji: '広範囲', hiragana: 'こうはんい', meaning: '广泛的' },
            { kanji: '包括的', hiragana: 'ほうかつてき', meaning: '全面的' },
            { kanji: '部分的', hiragana: 'ぶぶんてき', meaning: '部分的' },
            { kanji: '総合的に', hiragana: 'そうごうてき', meaning: '综合地' },
            { kanji: '個別的に', hiragana: 'こべつてき', meaning: '个别地' },
            { kanji: '体系的に', hiragana: 'たいけいてき', meaning: '系统地' },
            { kanji: '感覚的', hiragana: 'かんかんてき', meaning: '感觉地' },
            { kanji: '理論的', hiragana: 'りりんてき', meaning: '理论地' },
            { kanji: '経験的', hiragana: 'けいけんてき', meaning: '经验地' },
            { kanji: '直感', hiragana: 'ちょっかん', meaning: '直觉' },
            { kanji: '理屈', hiragana: 'りくつ', meaning: '道理' },
            { kanji: '理不尽', hiragana: 'りふじん', meaning: '不讲理' },
            { kanji: '筋道', hiragana: 'すじみち', meaning: '条理' },
            { kanji: '論理', hiragana: 'ろいろん', meaning: '逻辑' },
            { kanji: '整合性', hiragana: 'せいわせい', meaning: '整合性' },
            { kanji: '一貫性', hiragana: 'いっかんせい', meaning: '一贯性' },
            { kanji: '矛楯', hiragana: 'むじゅん', meaning: '矛盾' },
            { kanji: '齟齬', hiragana: 'そご', meaning: '不一致' },
            { kanji: '相容れない', hiragana: 'あいいれない', meaning: '不相容的' },
            { kanji: '両立', hiragana: 'りょうりつ', meaning: '两立' },
            { kanji: '調和', hiragana: 'ちょうわ', meaning: '调和' },
            { kanji: '均衡', hiragana: 'きんこう', meaning: '均衡' },
            { kanji: '平衡', hiragana: 'へいこう', meaning: '平衡' },
            { kanji: '対称', hiragana: 'たいしょう', meaning: '对称' }
        ],
        adjectives: [
            { kanji: '革新的な', hiragana: 'かくしんてきな', meaning: '革新的' },
            { kanji: '伝統的な', hiragana: 'でんとうてきな', meaning: '传统的' },
            { kanji: '現代的な', hiragana: 'げんだいてきな', meaning: '现代的' },
            { kanji: '古典的な', hiragana: 'こてんてきな', meaning: '古典的' },
            { kanji: '先進的な', hiragana: 'せんしんてきな', meaning: '先进的' },
            { kanji: '後進的な', hiragana: 'こうしんてきな', meaning: '后进的' },
            { kanji: '原始的な', hiragana: 'げんじてきな', meaning: '原始的' },
            { kanji: '文明的な', hiragana: 'ぶんめいてきな', meaning: '文明的' },
            { kanji: '野蛮な', hiragana: 'やばんな', meaning: '野蛮的' },
            { kanji: '文化的な', hiragana: 'ぶんかてきな', meaning: '文化的' },
            { kanji: '社会的な', hiragana: 'しゃかいてきな', meaning: '社会的' },
            { kanji: '個人的な', hiragana: 'こじんてきな', meaning: '个人的' },
            { kanji: '公共的な', hiragana: 'こうきょうてきな', meaning: '公共的' },
            { kanji: '私有の', hiragana: 'しゆうの', meaning: '私有的' },
            { kanji: '公有の', hiragana: 'こうゆうの', meaning: '公有的' },
            { kanji: '国際的な', hiragana: 'こくさいてきな', meaning: '国际的' },
            { kanji: '国内的な', hiragana: 'こくないてきな', meaning: '国内的' },
            { kanji: '世界的な', hiragana: 'せかいてきな', meaning: '世界的' },
            { kanji: '地域的な', hiragana: 'ちいきてきな', meaning: '地域的' },
            { kanji: 'グローバルな', hiragana: 'グローバルな', meaning: '全球的' },
            { kanji: 'ローカルな', hiragana: 'ローカルな', meaning: '地方的' },
            { kanji: '普遍的な', hiragana: 'ふへんてきな', meaning: '普遍的' },
            { kanji: '特殊な', hiragana: 'とくしゅな', meaning: '特殊的' },
            { kanji: '一般的な', hiragana: 'いっぱんな', meaning: '一般的' }
        ],
        verbs: [
            { kanji: '分析する', hiragana: 'ぶんせきする', meaning: '分析' },
            { kanji: '総合する', hiragana: 'そうごうする', meaning: '综合' },
            { kanji: '比較する', hiragana: 'ひかくする', meaning: '比较' },
            { kanji: '対比する', hiragana: 'たいひする', meaning: '对比' },
            { kanji: '対照する', hiragana: 'たいしょうする', meaning: '对照' },
            { kanji: '矛盾する', hiragana: 'むじゅんする', meaning: '矛盾' },
            { kanji: '一致する', hiragana: 'いっちする', meaning: '一致' },
            { kanji: '調和する', hiragana: 'ちょうわする', meaning: '调和' },
            { kanji: '対立する', hiragana: 'たいりつする', meaning: '对立' },
            { kanji: '均衡する', hiragana: 'きんこうする', meaning: '均衡' },
            { kanji: '調整する', hiragana: 'ちょうせいする', meaning: '调整' },
            { kanji: '修正する', hiragana: 'しゅうせいする', meaning: '修正' },
            { kanji: '改善する', hiragana: 'かいぜんする', meaning: '改善' },
            { kanji: '改良する', hiragana: 'かいりょうする', meaning: '改良' },
            { kanji: '改革する', hiragana: 'かいかくする', meaning: '改革' },
            { kanji: '革命する', hiragana: 'かくめいする', meaning: '革命' },
            { kanji: '進化', hiragana: 'しんか', meaning: '进化' },
            { kanji: '退化', hiragana: 'たいか', meaning: '退化' },
            { kanji: '発達', hiragana: 'はったつ', meaning: '发达' },
            { kanji: '発展', hiragana: 'はってん', meaning: '发展' },
            { kanji: '成長', hiragana: 'せいちょう', meaning: '成长' },
            { kanji: '成熟', hiragana: 'せいじゅく', meaning: '成熟' },
            { kanji: '老練', hiragana: 'ろうれん', meaning: '老练' },
            { kanji: '未熟', hiragana: 'みじゅく', meaning: '未熟' },
            { kanji: '熟達', hiragana: 'じゅくたつ', meaning: '熟练' },
            { kanji: '熟練', hiragana: 'じゅくれん', meaning: '熟练' },
            { kanji: '初心', hiragana: 'しょしん', meaning: '初心' },
            { kanji: '新手', hiragana: 'あらて', meaning: '新手' },
            { kanji: '玄人', hiragana: 'くろうと', meaning: '内行' },
            { kanji: '素人', hiragana: 'しろうと', meaning: '外行' }
        ]
    },
    N2: {
        nouns: [
            { kanji: '矛盾', hiragana: 'むじゅん', meaning: '矛盾' },
            { kanji: '曖昧', hiragana: 'あいまい', meaning: '曖昧' },
            { kanji: '優先', hiragana: 'ゆうせん', meaning: '优先' },
            { kanji: '深刻', hiragana: 'しんこく', meaning: '深刻的' },
            { kanji: '緊急', hiragana: 'きんきゅう', meaning: '紧急的' },
            { kanji: '重大', hiragana: 'じゅうだい', meaning: '重大的' },
            { kanji: '緊迫', hiragana: 'きんぱく', meaning: '紧迫的' },
            { kanji: '切実', hiragana: 'せつじつ', meaning: '迫切的' },
            { kanji: '鋭い', hiragana: 'するどい', meaning: '尖锐的' },
            { kanji: '微妙', hiragana: 'びみょう', meaning: '微妙的' },
            { kanji: '敏感', hiragana: 'びんかん', meaning: '敏感的' },
            { kanji: '鈍感', hiragana: 'どんかん', meaning: '迟钝的' },
            { kanji: '華麗', hiragana: 'かれい', meaning: '华丽的' },
            { kanji: '地味', hiragana: 'じみ', meaning: '朴素的' },
            { kanji: '鮮明', hiragana: 'せんめい', meaning: '鲜明的' },
            { kanji: '明瞭', hiragana: 'めいりょう', meaning: '明确的' },
            { kanji: '公平', hiragana: 'こうへい', meaning: '公平的' },
            { kanji: '公正', hiragana: 'こうせい', meaning: '公正的' },
            { kanji: '平等', hiragana: 'びょうどう', meaning: '平等的' },
            { kanji: '偏見', hiragana: 'へんけん', meaning: '偏见' },
            { kanji: '差別', hiragana: 'さべつ', meaning: '差别' },
            { kanji: '区別', hiragana: 'くべつ', meaning: '区别' },
            { kanji: '差異', hiragana: 'さい', meaning: '差异' },
            { kanji: '共通点', hiragana: 'きょうつうてん', meaning: '共同点' },
            { kanji: '相違点', hiragana: 'そういてん', meaning: '不同点' },
            { kanji: '類似点', hiragana: 'るいじてん', meaning: '类似点' },
            { kanji: '類似', hiragana: 'るいじ', meaning: '类似' },
            { kanji: '模倣', hiragana: 'もほう', meaning: '模仿' },
            { kanji: '創造', hiragana: 'そうぞう', meaning: '创造' },
            { kanji: '模造', hiragana: 'もぞう', meaning: '仿造' },
            { kanji: '本物', hiragana: 'ほんもの', meaning: '真货' },
            { kanji: '贋物', hiragana: 'にせもの', meaning: '赝品' },
            { kanji: '真正', hiragana: 'しんせい', meaning: '真正' },
            { kanji: '偽造', hiragana: 'ぎぞう', meaning: '伪造' },
            { kanji: '偽装', hiragana: 'ぎそう', meaning: '伪装' },
            { kanji: '隠蔽', hiragana: 'いんぺい', meaning: '隐瞒' },
            { kanji: '暴露', hiragana: 'ばくろ', meaning: '暴露' },
            { kanji: '発覚', hiragana: 'はっかく', meaning: '被发现' },
            { kanji: '露呈', hiragana: 'ろてい', meaning: '显露' },
            { kanji: '表面', hiragana: 'ひょうめん', meaning: '表面' },
            { kanji: '本質', hiragana: 'ほんしつ', meaning: '本质' },
            { kanji: '現象', hiragana: 'げんしょう', meaning: '现象' },
            { kanji: '実態', hiragana: 'じったい', meaning: '实际情况' },
            { kanji: '内幕', hiragana: 'ないまく', meaning: '内幕' },
            { kanji: '背景', hiragana: 'はいけい', meaning: '背景' },
            { kanji: '根源', hiragana: 'こんげん', meaning: '根源' },
            { kanji: '原因', hiragana: 'げんいん', meaning: '原因' },
            { kanji: '結果', hiragana: 'けっか', meaning: '结果' },
            { kanji: '理由', hiragana: 'りゆう', meaning: '理由' },
            { kanji: '根拠', hiragana: 'こんきょ', meaning: '根据' },
            { kanji: '証拠', hiragana: 'しょうこ', meaning: '证据' },
            { kanji: '痕跡', hiragana: 'こんせき', meaning: '痕迹' },
            { kanji: '実績', hiragana: 'じっせき', meaning: '实际成绩' },
            { kanji: '成果', hiragana: 'せいか', meaning: '成果' },
            { kanji: '効果', hiragana: 'こうか', meaning: '效果' },
            { kanji: '効用', hiragana: 'こうよう', meaning: '功用' },
            { kanji: '効能', hiragana: 'こうのう', meaning: '功效' },
            { kanji: '効力', hiragana: 'こうりょく', meaning: '效力' },
            { kanji: '無効', hiragana: 'むこう', meaning: '无效' },
            { kanji: '有効', hiragana: 'ゆうこう', meaning: '有效' },
            { kanji: '機能', hiragana: 'きのう', meaning: '功能' },
            { kanji: '作用', hiragana: 'さよう', meaning: '作用' }
        ],
        adjectives: [
            { kanji: '矛盾した', hiragana: 'むじゅんした', meaning: '矛盾的' },
            { kanji: '曖昧な', hiragana: 'あいまいな', meaning: '模糊的' },
            { kanji: '優先的な', hiragana: 'ゆうせんてきな', meaning: '优先的' },
            { kanji: '深刻的な', hiragana: 'しんこくてきな', meaning: '深刻的' },
            { kanji: '緊急的な', hiragana: 'きんきゅうてきな', meaning: '紧急的' },
            { kanji: '重大な', hiragana: 'じゅうだいな', meaning: '重大的' },
            { kanji: '微妙な', hiragana: 'びみょうな', meaning: '微妙的' },
            { kanji: '敏感な', hiragana: 'びんかんな', meaning: '敏感的' },
            { kanji: '鈍感な', hiragana: 'どんかんな', meaning: '迟钝的' },
            { kanji: '華麗な', hiragana: 'かれいな', meaning: '华丽的' },
            { kanji: '地味な', hiragana: 'じみな', meaning: '朴素的' },
            { kanji: '鮮明な', hiragana: 'せんめいな', meaning: '鲜明的' },
            { kanji: '明確な', hiragana: 'めいかくな', meaning: '明确的' },
            { kanji: '公平な', hiragana: 'こうへいな', meaning: '公平的' },
            { kanji: '公正な', hiragana: 'こうせいな', meaning: '公正的' },
            { kanji: '平等な', hiragana: 'びょうどうな', meaning: '平等的' },
            { kanji: '偏見のある', hiragana: 'けんけんのある', meaning: '有偏见的' },
            { kanji: '差別的な', hiragana: 'さべつてきな', meaning: '差别的' },
            { kanji: '創造的な', hiragana: 'そうぞうてきな', meaning: '创造性的' },
            { kanji: '模倣的な', hiragana: 'もほうてきな', meaning: '模仿性的' },
            { kanji: '真正な', hiragana: 'しんせいな', meaning: '真正的' },
            { kanji: '偽造の', hiragana: 'ぎぞうの', meaning: '伪造的' },
            { kanji: '隠蔽的な', hiragana: 'いんぺいてきな', meaning: '隐蔽性的' }
        ],
        verbs: [
            { kanji: '優先する', hiragana: 'ゆうせんする', meaning: '优先' },
            { kanji: '深刻化する', hiragana: 'しんこくかする', meaning: '深刻化' },
            { kanji: '緊急化する', hiragana: 'きんきゅうかする', meaning: '紧急化' },
            { kanji: '重大化する', hiragana: 'じゅうだいかする', meaning: '重大化' },
            { kanji: '敏感になる', hiragana: 'びんかんになる', meaning: '变得敏感' },
            { kanji: '鈍感になる', hiragana: 'どんかんになる', meaning: '变得迟钝' },
            { kanji: '華麗になる', hiragana: 'かれいになる', meaning: '变得华丽' },
            { kanji: '鮮明になる', hiragana: 'せんめいになる', meaning: '变得鲜明' },
            { kanji: '明確になる', hiragana: 'めいかくになる', meaning: '变得明确' },
            { kanji: '公平にする', hiragana: 'こうへいにする', meaning: '公平处理' },
            { kanji: '公正にする', hiragana: 'こうせいにする', meaning: '公正处理' },
            { kanji: '平等にする', hiragana: 'びょうどうにする', meaning: '平等处理' },
            { kanji: '差別する', hiragana: 'さべつする', meaning: '差别对待' },
            { kanji: '創造する', hiragana: 'そうぞうする', meaning: '创造' },
            { kanji: '模倣する', hiragana: 'もほうする', meaning: '模仿' },
            { kanji: '偽造する', hiragana: 'ぎぞうする', meaning: '伪造' },
            { kanji: '隠蔽する', hiragana: 'いんぺいする', meaning: '隐瞒' },
            { kanji: '暴露する', hiragana: 'ばくろする', meaning: '暴露' },
            { kanji: '発覚する', hiragana: 'はっかくする', meaning: '被发现' },
            { kanji: '露呈する', hiragana: 'ろていする', meaning: '显露' }
        ]
    },
    N1: {
        nouns: [
            { kanji: '矛盾', hiragana: 'むじゅん', meaning: '矛盾' },
            { kanji: '曖昧', hiragana: 'あいまい', meaning: '曖昧' },
            { kanji: '優先', hiragana: 'ゆうせん', meaning: '优先' },
            { kanji: '深刻', hiragana: 'しんこく', meaning: '深刻的' },
            { kanji: '緊急', hiragana: 'きんきゅう', meaning: '紧急的' },
            { kanji: '重大', hiragana: 'じゅうだい', meaning: '重大的' },
            { kanji: '緊迫', hiragana: 'きんぱく', meaning: '紧迫的' },
            { kanji: '切実', hiragana: 'せつじつ', meaning: '迫切的' },
            { kanji: '鋭い', hiragana: 'するどい', meaning: '尖锐的' },
            { kanji: '微妙', hiragana: 'びみょう', meaning: '微妙的' },
            { kanji: '敏感', hiragana: 'びんかん', meaning: '敏感的' },
            { kanji: '鈍感', hiragana: 'どんかん', meaning: '迟钝的' },
            { kanji: '華麗', hiragana: 'かれい', meaning: '华丽的' },
            { kanji: '地味', hiragana: 'じみ', meaning: '朴素的' },
            { kanji: '鮮明', hiragana: 'せんめい', meaning: '鲜明的' },
            { kanji: '明瞭', hiragana: 'めいりょう', meaning: '明确的' },
            { kanji: '公平', hiragana: 'こうへい', meaning: '公平的' },
            { kanji: '公正', hiragana: 'こうせい', meaning: '公正的' },
            { kanji: '平等', hiragana: 'びょうどう', meaning: '平等的' },
            { kanji: '偏見', hiragana: 'へんけん', meaning: '偏见' },
            { kanji: '差別', hiragana: 'さべつ', meaning: '差别' },
            { kanji: '区別', hiragana: 'くべつ', meaning: '区别' },
            { kanji: '差異', hiragana: 'さい', meaning: '差异' },
            { kanji: '共通点', hiragana: 'きょうつうてん', meaning: '共同点' },
            { kanji: '相違点', hiragana: 'そういてん', meaning: '不同点' },
            { kanji: '類似点', hiragana: 'るいじてん', meaning: '类似点' },
            { kanji: '類似', hiragana: 'るいじ', meaning: '类似' },
            { kanji: '模倣', hiragana: 'もほう', meaning: '模仿' },
            { kanji: '創造', hiragana: 'そうぞう', meaning: '创造' },
            { kanji: '模造', hiragana: 'もぞう', meaning: '仿造' },
            { kanji: '本物', hiragana: 'ほんもの', meaning: '真货' },
            { kanji: '贋物', hiragana: 'にせもの', meaning: '赝品' },
            { kanji: '真正', hiragana: 'しんせい', meaning: '真正' },
            { kanji: '偽造', hiragana: 'ぎぞう', meaning: '伪造' },
            { kanji: '偽装', hiragana: 'ぎそう', meaning: '伪装' },
            { kanji: '隠蔽', hiragana: 'いんぺい', meaning: '隐瞒' },
            { kanji: '暴露', hiragana: 'ばくろ', meaning: '暴露' },
            { kanji: '発覚', hiragana: 'はっかく', meaning: '被发现' },
            { kanji: '露呈', hiragana: 'ろてい', meaning: '显露' },
            { kanji: '表面', hiragana: 'ひょうめん', meaning: '表面' },
            { kanji: '本質', hiragana: 'ほんしつ', meaning: '本质' },
            { kanji: '現象', hiragana: 'げんしょう', meaning: '现象' },
            { kanji: '実態', hiragana: 'じったい', meaning: '实际情况' },
            { kanji: '内幕', hiragana: 'ないまく', meaning: '内幕' },
            { kanji: '背景', hiragana: 'はいけい', meaning: '背景' },
            { kanji: '根源', hiragana: 'こんげん', meaning: '根源' },
            { kanji: '原因', hiragana: 'げんいん', meaning: '原因' },
            { kanji: '結果', hiragana: 'けっか', meaning: '结果' },
            { kanji: '理由', hiragana: 'りゆう', meaning: '理由' },
            { kanji: '根拠', hiragana: 'こんきょ', meaning: '根据' },
            { kanji: '証拠', hiragana: 'しょうこ', meaning: '证据' },
            { kanji: '痕跡', hiragana: 'こんせき', meaning: '痕迹' },
            { kanji: '実績', hiragana: 'じっせき', meaning: '实际成绩' },
            { kanji: '成果', hiragana: 'せいか', meaning: '成果' },
            { kanji: '効果', hiragana: 'こうか', meaning: '效果' },
            { kanji: '効用', hiragana: 'こうよう', meaning: '功用' },
            { kanji: '効能', hiragana: 'こうのう', meaning: '功效' },
            { kanji: '効力', hiragana: 'こうりょく', meaning: '效力' },
            { kanji: '無効', hiragana: 'むこう', meaning: '无效' },
            { kanji: '有効', hiragana: 'ゆうこう', meaning: '有效' },
            { kanji: '機能', hiragana: 'きのう', meaning: '功能' },
            { kanji: '作用', hiragana: 'さよう', meaning: '作用' },
            { kanji: '副作用', hiragana: 'ふくさよう', meaning: '副作用' },
            { kanji: '反作用', hiragana: 'はんさよう', meaning: '反作用' },
            { kanji: '影響', hiragana: 'えいきょう', meaning: '影响' },
            { kanji: '反響', hiragana: 'はんきょう', meaning: '反响' },
            { kanji: '反応', hiragana: 'はんのう', meaning: '反应' },
            { kanji: '対応', hiragana: 'たいおう', meaning: '对应' },
            { kanji: '対処', hiragana: 'たいしょ', meaning: '处理' },
            { kanji: '処理', hiragana: 'しょり', meaning: '处理' },
            { kanji: '解決', hiragana: 'かいけつ', meaning: '解决' },
            { kanji: '克服', hiragana: 'こくふく', meaning: '克服' },
            { kanji: '挽回', hiragana: 'ばんかい', meaning: '挽回' },
            { kanji: '回復', hiragana: 'かいふく', meaning: '恢复' },
            { kanji: '復興', hiragana: 'ふっこう', meaning: '复兴' },
            { kanji: '再生', hiragana: 'さいせい', meaning: '再生' },
            { kanji: '復活', hiragana: 'ふっかつ', meaning: '复活' },
            { kanji: '再起', hiragana: 'さいき', meaning: '东山再起' }
        ],
        adjectives: [
            { kanji: '矛盾した', hiragana: 'むじゅんした', meaning: '矛盾的' },
            { kanji: '曖昧な', hiragana: 'あいまいな', meaning: '模糊的' },
            { kanji: '優先的な', hiragana: 'ゆうせんてきな', meaning: '优先的' },
            { kanji: '深刻的な', hiragana: 'しんこくてきな', meaning: '深刻的' },
            { kanji: '緊急的な', hiragana: 'きんきゅうてきな', meaning: '紧急的' },
            { kanji: '重大な', hiragana: 'じゅうだいな', meaning: '重大的' },
            { kanji: '微妙な', hiragana: 'びみょうな', meaning: '微妙的' },
            { kanji: '敏感な', hiragana: 'びんかんな', meaning: '敏感的' },
            { kanji: '鈍感な', hiragana: 'どんかんな', meaning: '迟钝的' },
            { kanji: '華麗な', hiragana: 'かれいな', meaning: '华丽的' },
            { kanji: '地味な', hiragana: 'じみな', meaning: '朴素的' },
            { kanji: '鮮明な', hiragana: 'せんめいな', meaning: '鲜明的' },
            { kanji: '明確な', hiragana: 'めいかくな', meaning: '明确的' },
            { kanji: '公平な', hiragana: 'こうへいな', meaning: '公平的' },
            { kanji: '公正な', hiragana: 'こうせいな', meaning: '公正的' },
            { kanji: '平等な', hiragana: 'びょうどうな', meaning: '平等的' },
            { kanji: '偏見のある', hiragana: 'けんけんのある', meaning: '有偏见的' },
            { kanji: '差別的な', hiragana: 'さべつてきな', meaning: '差别的' },
            { kanji: '創造的な', hiragana: 'そうぞうてきな', meaning: '创造性的' },
            { kanji: '模倣的な', hiragana: 'もほうてきな', meaning: '模仿性的' },
            { kanji: '真正な', hiragana: 'しんせいな', meaning: '真正的' },
            { kanji: '隠蔽的な', hiragana: 'いんぺいてきな', meaning: '隐蔽性的' },
            { kanji: '複雑な', hiragana: 'ふくざつな', meaning: '复杂的' },
            { kanji: '単純な', hiragana: 'たんじゅんな', meaning: '单纯的' },
            { kanji: '具体的な', hiragana: 'ぐたいてきな', meaning: '具体的' },
            { kanji: '抽象的な', hiragana: 'ちゅうしょうてきな', meaning: '抽象的' },
            { kanji: '主观的な', hiragana: 'しゅかんてきな', meaning: '主观的' },
            { kanji: '客观的な', hiragana: 'きゃっかんてきな', meaning: '客观的' },
            { kanji: '積極的な', hiragana: 'せっきょくてきな', meaning: '积极的' },
            { kanji: '消極的な', hiragana: 'しょうきょくてきな', meaning: '消极的' }
        ],
        verbs: [
            { kanji: '優先する', hiragana: 'ゆうせんする', meaning: '优先' },
            { kanji: '深刻化する', hiragana: 'しんこくかする', meaning: '深刻化' },
            { kanji: '緊急化する', hiragana: 'きんきゅうかする', meaning: '紧急化' },
            { kanji: '重大化する', hiragana: 'じゅうだいかする', meaning: '重大化' },
            { kanji: '敏感になる', hiragana: 'びんかんになる', meaning: '变得敏感' },
            { kanji: '鈍感になる', hiragana: 'どんかんになる', meaning: '变得迟钝' },
            { kanji: '華麗になる', hiragana: 'かれいになる', meaning: '变得华丽' },
            { kanji: '鮮明になる', hiragana: 'せんめいになる', meaning: '变得鲜明' },
            { kanji: '明確になる', hiragana: 'めいかくになる', meaning: '变得明确' },
            { kanji: '公平にする', hiragana: 'こうへいにする', meaning: '公平处理' },
            { kanji: '公正にする', hiragana: 'こうせいにする', meaning: '公正处理' },
            { kanji: '平等にする', hiragana: 'びょうどうにする', meaning: '平等处理' },
            { kanji: '差別する', hiragana: 'さべつする', meaning: '差别对待' },
            { kanji: '創造する', hiragana: 'そうぞうする', meaning: '创造' },
            { kanji: '模倣する', hiragana: 'もほうする', meaning: '模仿' },
            { kanji: '偽造する', hiragana: 'ぎぞうする', meaning: '伪造' },
            { kanji: '隠蔽する', hiragana: 'いんぺいする', meaning: '隐瞒' },
            { kanji: '暴露する', hiragana: 'ばくろする', meaning: '暴露' },
            { kanji: '発覚する', hiragana: 'はっかくする', meaning: '被发现' },
            { kanji: '露呈する', hiragana: 'ろていする', meaning: '显露' },
            { kanji: '対応する', hiragana: 'たいおうする', meaning: '对应' },
            { kanji: '対処する', hiragana: 'たいしょする', meaning: '处理' },
            { kanji: '処理する', hiragana: 'しょりする', meaning: '处理' },
            { kanji: '解決する', hiragana: 'かいけつする', meaning: '解决' },
            { kanji: '克服する', hiragana: 'こくふくする', meaning: '克服' },
            { kanji: '挽回する', hiragana: 'ばんかいする', meaning: '挽回' },
            { kanji: '回復する', hiragana: 'かいふくする', meaning: '恢复' },
            { kanji: '復興する', hiragana: 'ふっこうする', meaning: '复兴' },
            { kanji: '再生する', hiragana: 'さいせいする', meaning: '再生' },
            { kanji: '復活する', hiragana: 'ふっかつする', meaning: '复活' }
        ]
    }
};

const grammarByLevel = {
    N5: [
        { pattern: 'は', description: '主题标记', example: '私は学生です。' },
        { pattern: 'が', description: '主语/对象语标记', example: '日本語がわかります。' },
        { pattern: 'を', description: '宾语标记', example: '本を読みます。' },
        { pattern: 'に', description: '时间/地点/方向标记', example: '学校に行きます。' },
        { pattern: 'で', description: '动作场所标记', example: '図書館で勉強します。' },
        { pattern: 'と', description: '和...一起', example: '友達と行きます。' },
        { pattern: 'や', description: '不完全列举', example: 'りんやばななど。' },
        { pattern: 'から', description: '起点', example: '日本からきました。' },
        { pattern: 'まで', description: '终点', example: '東京まで行きます。' },
        { pattern: 'も', description: '也', example: '私も行きます。' },
        { pattern: 'だけ', description: '只', example: 'それだけですか。' },
        { pattern: 'しか', description: '只（负面）', example: 'それしか知りません。' },
        { pattern: 'の', description: '所有格', example: '私のです。' },
        { pattern: 'へ', description: '方向', example: '東京へ行きます。' }
    ],
    N4: [
        { pattern: 'ので', description: '因为...所以', example: '忙しいので、行けません。' },
        { pattern: 'のに', description: '用于...', example: '有这么好的东西。' },
        { pattern: 'が', description: '但是', example: '行きたいが、時間がない。' },
        { pattern: 'ても', description: '即使...也', example: '雨ても行きます。' },
        { pattern: 'でも', description: '即使...也', example: '子供でもわかります。' },
        { pattern: 'たら', description: '如果...就', example: '雨だったら、家にあります。' },
        { pattern: 'なら', description: '如果...的话', example: '上海に行くなら、案内します。' },
        { pattern: 'ば', description: '如果...就', example: '晴れば、遊びに行きます。' },
        { pattern: 'ために', description: '为了', example: '旅行ために、お金を貯めます。' },
        { pattern: 'ように', description: '为了...', example: '忘れないように、メモします。' },
        { pattern: '通过', description: '通过...', example: '友達を通して、彼女を知りました。' },
        { pattern: 'について', description: '关于...', example: '日本の文化について話します。' },
        { pattern: 'によって', description: '根据...', example: '人によって、意見が違います。' },
        { pattern: 'にとって', description: '对...来说', example: '私にとって、仕事は重要です。' }
    ],
    N3: [
        { pattern: '一方で', description: '一方面...另一方面', example: '彼は偉い。一方で、傲慢だ。' },
        { pattern: 'それに対して', description: '与此相对', example: 'Ａは正しい。それに対して、Ｂは間違っている。' },
        { pattern: '一方だ', description: '一直...下去', example: '問題は増える一方だ。' },
        { pattern: '反面', description: '另一方面', example: '優秀な反面、協調性がない。' },
        { pattern: '一方では', description: '一方面', example: '一方では資金が足りない。' },
        { pattern: '他方', description: '另一方面', example: '費用は高い。他方、品質は良い。' },
        { pattern: 'かえって', description: '反而', example: '説明を聞けば、かえってわからなくなる。' },
        { pattern: 'むしろ', description: '不如说', example: '好きというより、むしろ嫌いだ。' },
        { pattern: 'さもなければ', description: '否则', example: ' 빨리行けば間に合う。さもなければ、遅刻する。' },
        { pattern: 'ものの', description: '虽然...但是', example: '見たことはあるものの、名前は知らない。' },
        { pattern: 'ものを', description: '本应该...却', example: '言えばいいものを、言わない。' },
        { pattern: 'からには', description: '既然...就', example: '学生であるからには、勉強すべきだ。' },
        { pattern: '以上', description: '既然...就', example: 'ここまで読んだ以上、終わりまで読みなさい。' }
    ],
    N2: [
        { pattern: 'に関して', description: '关于...', example: 'この問題に関して、説明します。' },
        { pattern: 'に応して', description: '根据...', example: '状況に応して、変わりましょう。' },
        { pattern: 'と共に', description: '和...一起', example: '家族と共に、住みます。' },
        { pattern: 'に反して', description: '与...相反', example: '予想に反して、易しかった。' },
        { pattern: 'に沿って', description: '沿着...', example: '川に沿って、歩きます。' },
        { pattern: 'に分けて', description: '把...分开', example: 'グループに分けて、話し合います。' },
        { pattern: 'にわたって', description: '涉及...', example: '三時間にわたって、会議がありました。' },
        { pattern: 'に先立って', description: '在...之前', example: '会議に先立って、資料を準備します。' },
        { pattern: 'に伴って', description: '随着...', example: '時代に伴って、変わります。' },
        { pattern: 'に反比例して', description: '与...成反比', example: '大きさに反比例して、値は変わります。' },
        { pattern: 'に至るまで', description: '直到...', example: '参加者名簿に至るまで、作成しました。' },
        { pattern: 'を控えて', description: '在...之前', example: '試合を控えて、練習を重ねています。' },
        { pattern: 'を通じて', description: '整个...期间', example: '人生をを通じて学び続けます。' },
        { pattern: 'を踏まえて', description: '基于...', example: '経験を踏まえて、改善します。' }
    ],
    N1: [
        { pattern: 'に基づいて', description: '根据...', example: '法律に基づいて、処罰します。' },
        { pattern: 'に応じて', description: '根据...', example: '収入に応じて、支出を調整します。' },
        { pattern: 'に伴って', description: '随着...', example: '工業化に伴って、環境問題も深刻化した。' },
        { pattern: 'につれて', description: '随着...', example: '年を取るにつれて、記憶力が衰えた。' },
        { pattern: 'に沿って', description: '沿着...', example: '計画に沿って、作業を進めます。' },
        { pattern: 'に伴って', description: '伴随...', example: '人口増加に伴って、住房問題も深刻化している。' },
        { pattern: 'んばかりに', description: '几乎要...', example: '泣きんばかりの顔で訴えた。' },
        { pattern: 'んがために', description: '为了...', example: '生きんがために、彼は拼命に働いた。' },
        { pattern: 'ずにはいられない', description: '不得不...', example: 'この景色を見ると、感動せずにはいられない。' },
        { pattern: 'ざるを得ない', description: '不得不...', example: '興味がないざるを得ない。' },
        { pattern: 'かねない', description: '有可能...', example: 'このままだと、事件は悪化かねない。' },
        { pattern: 'っこない', description: '不可能...', example: 'こんな難しい問題は、私には出来っこない。' },
        { pattern: 'まくる', description: '拼命地...', example: '雨の日も風の日も、彼は走りまくる。' },
        { pattern: 'や否や', description: '刚...就...', example: '彼は登場や否や、拍手が起こった。' }
    ]
};

function generateWrongOptions(correctHiragana, vocabList, type) {
    const wrongOptions = [];
    const allItems = vocabList.nouns.concat(vocabList.adjectives).concat(vocabList.verbs);
    
    const shuffled = allItems
        .filter(item => item.hiragana !== correctHiragana)
        .sort(() => 0.5 - Math.random())
        .slice(0, 10);
    
    wrongOptions.push(...shuffled.slice(0, 3).map(item => item.hiragana));
    
    while (wrongOptions.length < 3) {
        const randomHiragana = generateRandomSyllable();
        if (!wrongOptions.includes(randomHiragana) && randomHiragana !== correctHiragana) {
            wrongOptions.push(randomHiragana);
        }
    }
    
    return wrongOptions.slice(0, 3).sort(() => 0.5 - Math.random());
}

function generateRandomSyllable() {
    const syllables = ['あ', 'い', 'う', 'え', 'お', 'か', 'き', 'く', 'け', 'こ', 'さ', 'し', 'す', 'せ', 'そ', 'た', 'ち', 'つ', 'て', 'と', 'な', 'に', 'ぬ', 'ね', 'の', 'は', 'ひ', 'ふ', 'へ', 'ほ', 'ま', 'み', 'む', 'め', 'も', 'や', 'ゆ', 'よ', 'ら', 'り', 'る', 'れ', 'ろ', 'わ', 'を', 'ん'];
    return syllables[Math.floor(Math.random() * syllables.length)];
}

function generateVocabQuestion(level, vocabItem, vocabList) {
    const wrongOptions = generateWrongOptions(vocabItem.hiragana, vocabList, vocabItem.type);
    const options = wrongOptions.slice(0, 3);
    const correctIndex = Math.floor(Math.random() * 4);
    options.splice(correctIndex, 0, vocabItem.hiragana);
    
    const optionLetters = ['A', 'B', 'C', 'D'];
    
    const questionTemplates = [
        `{kanji}の読み方は何ですか。`,
        `{kanji}の意味は何ですか。`,
        `{kanji}は何と読みますか。`,
        `{kanji}はどのような意味ですか。`
    ];
    
    const questionTemplate = questionTemplates[Math.floor(Math.random() * questionTemplates.length)];
    const question = questionTemplate.replace('{kanji}', vocabItem.kanji);
    
    return {
        level: level,
        type: 'vocab',
        question: question,
        option_a: options[0],
        option_b: options[1],
        option_c: options[2],
        option_d: options[3],
        correct_answer: optionLetters[correctIndex],
        explanation: vocabItem.kanji + '的读音是' + vocabItem.hiragana + '，意思是' + vocabItem.meaning + '。'
    };
}

function generateGrammarQuestion(level, grammarItem) {
    const patterns = [
        'この文法で（　）に入る正しいものは何ですか。',
        '（　）に入る最も適切な表現はどれですか。',
        '文の（　）に何を入れますか。',
        '次の文の（　）に入る言い方は何ですか。'
    ];
    
    const contexts = [
        '昨日友達に映画に誘われましたが、用事があったので（　）。',
        '雨が降り始めたので、傘がない私たちは（　）。',
        '彼は毎日練習しているのに、上達する様子が（　）。',
        'この問題は難しいので、私たちだけでは（　）。',
        '時間があれば、手伝って（　）。',
        '彼女は何度も失敗したが、（　）挑戦し続けた。',
        'この機械は操作が簡単で、子供でも（　）。',
        '彼は英語が話せないどころか、（　）很多言語が話せます。'
    ];
    
    const question = contexts[Math.floor(Math.random() * contexts.length)];
    const template = patterns[Math.floor(Math.random() * patterns.length)];
    
    const option1 = grammarItem.pattern;
    const option2 = generateSimilarPattern(grammarItem.pattern);
    const option3 = generateDifferentPattern();
    const option4 = generateRandomPattern();
    
    const options = [option1, option2, option3, option4];
    const shuffledOptions = options
        .map((opt, idx) => ({ opt, idx }))
        .sort(() => 0.5 - Math.random())
        .map(item => item.opt);
    
    const optionLetters = ['A', 'B', 'C', 'D'];
    const correctAnswer = optionLetters[shuffledOptions.indexOf(option1)];
    
    return {
        level: level,
        type: 'grammar',
        question: template + '\\n\\n"' + question + '"',
        option_a: shuffledOptions[0],
        option_b: shuffledOptions[1],
        option_c: shuffledOptions[2],
        option_d: shuffledOptions[3],
        correct_answer: correctAnswer,
        explanation: grammarItem.pattern + grammarItem.description + '。' + grammarItem.example
    };
}

function generateSimilarPattern(pattern) {
    const variations = {
        'は': 'が', 'が': 'は', 'を': 'に', 'に': 'で', 'で': 'に',
        'と': 'や', 'や': 'と', 'から': 'まで', 'まで': 'から',
        'ので': 'から', 'のに': 'ために', 'が': 'けれど',
        'ても': 'でも', 'でも': 'ても', 'たら': 'ば',
        'なら': 'ば', 'ために': 'ように', 'ように': 'ために',
        '通过': 'について', 'について': 'によって',
        'によって': 'にとって', 'にとって': 'にとって'
    };
    return variations[pattern] || 'が';
}

function generateDifferentPattern() {
    const patterns = ['は', 'が', 'を', 'に', 'で', 'と', 'や', 'から', 'まで', 'も'];
    return patterns[Math.floor(Math.random() * patterns.length)];
}

function generateRandomPattern() {
    const patterns = ['へ', 'の', 'だけ', 'しか', 'ので', 'のに', 'たら', 'なら', 'ば'];
    return patterns[Math.floor(Math.random() * patterns.length)];
}

function generateQuestions() {
    const questions = { questions: [] };
    const questionsPerLevel = 1000;
    const vocabRatio = 0.8;
    
    for (const level of ['N5', 'N4', 'N3', 'N2', 'N1']) {
        console.log(`Generating ${level} questions...`);
        
        const vocabList = vocabByLevel[level];
        const grammarList = grammarByLevel[level];
        const allVocab = vocabList.nouns.concat(vocabList.adjectives).concat(vocabList.verbs);
        
        let vocabCount = 0;
        let grammarCount = 0;
        
        for (let i = 0; i < questionsPerLevel; i++) {
            if (Math.random() < vocabRatio && vocabCount < Math.floor(questionsPerLevel * vocabRatio)) {
                const vocabItem = allVocab[i % allVocab.length];
                questions.questions.push(generateVocabQuestion(level, vocabItem, vocabList));
                vocabCount++;
            } else if (grammarCount < Math.floor(questionsPerLevel * (1 - vocabRatio))) {
                const grammarItem = grammarList[grammarCount % grammarList.length];
                questions.questions.push(generateGrammarQuestion(level, grammarItem));
                grammarCount++;
            } else {
                const vocabItem = allVocab[i % allVocab.length];
                questions.questions.push(generateVocabQuestion(level, vocabItem, vocabList));
                vocabCount++;
            }
        }
        
        console.log(`${level}: ${vocabCount} vocab questions, ${grammarCount} grammar questions`);
    }
    
    fs.writeFileSync('questions-expanded.json', JSON.stringify(questions, null, 2), 'utf8');
    console.log('Questions saved to questions-expanded.json');
    console.log(`Total questions: ${questions.questions.length}`);
}

generateQuestions();
